export const darkTheme = {
  dfaultColor: "#fff",
  bgColor: "#0D1117",
  ContainColor: "#161B22",
  cardColor: "#22272E",
  textareaColor: "#161b22",
  textColor: "#C9D1D9",
  subTextColor: "#C9D1D9",
  inputTextColor: "#C9D1D9",
  borderColor: "#fff",
  placeholderColor: "#fff",
  inputColor: "#161B22",
  iconColor: "#C9D1D9",
  iconColorB: "#fff",
  cardBtnColorA: "#C9D1D9",
  cardBtnColorB: "#C9D1D9",
  btnTextColor: "#0D1117",
  btnColor: "#000",
  modalBgColor: "#000",
  storyBox: "rgba(0, 0, 0, 0.5)",
  storyBorder: "rgba(0, 0, 0, 0.2)",
  albumBorder: "rgba(255, 255, 255, 0.1)",
  boxShadow: "rgba(0, 0, 0, 0.8)",
};
export const lightTheme = {
  dfaultColor: "#111",
  bgColor: "var(--color-white)",
  ContainColor: "var(--color-white)",
  cardColor: "var(--color-light-gray-02)",
  textareaColor: "var(--color-light-gray-02)",
  textColor: "#111",
  subTextColor: "var(--color-gray-01)",
  inputTextColor: "#fff",
  borderColor: "#fff",
  placeholderColor: "var(--color-gray-01)",
  inputColor: "#ddd",
  iconColor: "#000",
  iconColorB: "#000",
  cardBtnColorA: "var(--color-facebookblue)",
  cardBtnColorB: "var(--color-light-gray-01)",
  btnTextColor: "#0D1117",
  btnColor: "#fff",
  modalBgColor: "rgba(0, 0, 0, 0.9)",
  storyBox: "var(--color-white)",
  storyBorder: "var(--color-white)",
  albumBorder: "var(--color-light-gray-02)",
  boxShadow: "rgba(182, 182, 182, 0.8)",
};
